<?php
/**
 * @namespace
 */
namespace de\imxnet\imxplatformphp\varnish;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-01 at 19:46:28.
 */
class DefinitionsProviderTest extends \de\codenamephp\platform\test\TestCase {

  /**
   * @var \de\codenamephp\platform\di\Container
   */
  private $di = null;

  protected function setUp() {
    $containerBuilder = new \de\codenamephp\platform\di\ContainerBuilder();
    $containerBuilder->addDefinitionsByProvider(new DefinitionsProvider());
    $this->di = $containerBuilder->build();
  }

  public function testCanGetInstanceofiBan() {
    self::assertInstanceOf(invalidation\iBan::class, $this->di->get(invalidation\iBan::class));
  }

  public function testCanGetInstanceOfVarnishClient_withLocalhostAsServer() {
    $varnish = $this->di->get(\FOS\HttpCache\ProxyClient\Varnish::class);

    self::assertInstanceOf(\FOS\HttpCache\ProxyClient\Varnish::class, $varnish);
    self::assertAttributeEquals(['http://127.0.0.1'], 'servers', $varnish);
  }
}
